### ISSUE TITLE
Websocket example mentioned in the examples directory fails with Invalid response status 404 not found.

### ISSUE THREAD

**Issue by pranavpadmasali** [thefstock/FirstockPy#22]
I'm trying to run the example for the WebSocket in the example directory. I've modified the input required for the program to pass my correct credentials.

```
$poetry run python -m examples.websocket.run
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/pranavpadmasali/PycharmProjects/FirstockPy/client/examples/websocket/run.py", line 48, in <module>
    ws.connect('******', response.actid)
  File "/Users/pranavpadmasali/PycharmProjects/FirstockPy/client/py_client/websocket/client.py", line 108, in connect
    return super().connect()
  File "/Users/pranavpadmasali/Library/Caches/pypoetry/virtualenvs/py-client-ni1qpx8_-py3.9/lib/python3.9/site-packages/ws4py/client/__init__.py", line 239, in connect
    self.process_response_line(response_line)
  File "/Users/pranavpadmasali/Library/Caches/pypoetry/virtualenvs/py-client-ni1qpx8_-py3.9/lib/python3.9/site-packages/ws4py/client/__init__.py", line 307, in process_response_line
    raise HandshakeError("Invalid response status: %s %s" % (code, status))
ws4py.exc.HandshakeError: Invalid response status: b'404' b'Not Found'
```
Can someone help me to get the correct URL to connect to websocket. Currently the websocket URL I'm passing is `'wss://norenapi.thefirstock.com/NorenWSTP'`
Note:- with the same credentials I'm able to use other apis successfully.

**Comment by aswinrp** [comment]
Add a / to the url at the end. 
wss://norenapi.thefirstock.com/NorenWSTP/
This error should be fixed. @pranavpadmasali

**Comment by pranavpadmasali** [comment]
Hey @aswinrp, Thanks for this, it worked. Don't know how I missed it xD.
